import fs from 'node:fs';import path from 'node:path';import vm from 'node:vm';import {contentFor} from './content-model.mjs';
const root=process.cwd();const fail=[];const read=p=>fs.readFileSync(path.join(root,p),'utf8');const must=(ok,msg)=>{if(!ok)fail.push(msg)};const htmlFiles=[];
function walk(dir){for(const name of fs.readdirSync(dir)){const p=path.join(dir,name),full=path.join(root,p),st=fs.statSync(full);if(st.isDirectory())walk(p);else if(name.endsWith('.html'))htmlFiles.push(p)}}walk('resources');
const box={window:{}};vm.runInNewContext(read('data.js'),box);const D=box.window.CHITRAMITRA,langs=Object.keys(D.languages),formats=Object.keys(D.formats);
must(langs.length===6,'Language matrix must contain exactly 6 languages');must(D.topics.length===20,'Topic matrix must contain exactly 20 topics');must(formats.length===5,'Format matrix must contain exactly 5 formats');must(htmlFiles.length===601,'Generated HTML count must be 601 including resources/index.html');
const index=read('index.html'),app=read('app.js'),styles=read('styles.css'),resourceCss=read('resource.css');
must(index.includes('id="language"')&&index.includes('id="age"')&&index.includes('id="search"'),'Primary controls missing');must(index.includes('id="searchBtn"'),'Search button missing');must(index.includes('id="menu"'),'Mobile menu button missing');must((index.match(/<button\b/g)||[]).length>=7,'Expected resource filter/search/menu buttons missing');must(app.includes('searchBtn')&&app.includes('filters button')&&app.includes('topicList'),'Interactive resource controls not wired');must(app.includes("menu.onclick")&&app.includes('nav.classList.toggle'),'Mobile menu is not wired');must(app.includes('topicFilter')&&app.includes('data-topic'),'Topic filtering is not wired');must(styles.includes('.topbar nav.open'),'Mobile menu open state styling missing');must(resourceCss.includes('@page{size:A4'),'A4 print CSS missing');must(!/WorthGo/i.test(index+app+styles+read('data.js')),'Legacy WorthGo branding leaked into primary UI');must(!/lorem ipsum|coming soon|TODO|FIXME/i.test(index+app+styles),'Placeholder content remains in primary UI');
for(const [t] of D.topics){const c=contentFor(t);must(t==='alphabet'?c.examples.length===26:c.examples.length>=12,`Topic ${t} must contain at least 12 learning items`);must(c.skill.length>20,`Topic ${t} has insufficient learning objective content`)}
for(const l of langs){
  const a=contentFor('alphabet',l);
  for(const [group,chars] of Object.entries(a.groups))must(chars.length>0,\`Alphabet group \${l}/\${group} is empty\`);
  if(l==='en')must(a.groups.letters.length===26,'English alphabet must contain 26 letters');
  if(l==='ta')must(a.groups['உயிர்மெய் சேர்க்கைகள்'].length===216,'Tamil uyirmei matrix must contain 216 combinations');
  if(l==='te'){const n=a.groups['హల్లులు'].length;must(n>0,'Telugu consonant set is empty');must(a.groups['గుణింతాలు (క్రమబద్ధమైన అభ్యాసం)'].length===n*13,'Telugu gunintalu matrix is incomplete');must(a.groups['అనుస్వార-విసర్గ అభ్యాసం'].length===n*2,'Telugu anusvara-visarga matrix is incomplete')}
  if(l==='hi'){const n=a.groups['व्यंजन'].length;must(n>0,'Hindi consonant set is empty');must(a.groups['मात्रा और हलन्त अभ्यास'].length===n*15,'Hindi matra matrix is incomplete')}
  if(l==='kn'){const n=a.groups['ವ್ಯಂಜನಗಳು'].length;must(n>0,'Kannada consonant set is empty');must(a.groups['ಸ್ವರಚಿಹ್ನೆ ಮತ್ತು ಒತ್ತಕ್ಷರ ಅಭ್ಯಾಸ'].length===n*15,'Kannada vowel-sign matrix is incomplete')}
  if(l==='ml'){const n=a.groups['വ്യഞ്ജനങ്ങൾ'].length;must(n>0,'Malayalam consonant set is empty');must(a.groups['സ്വരചിഹ്നവും സംയുക്താക്ഷര-ചിഹ്ന അഭ്യാസവും'].length===n*15,'Malayalam vowel-sign matrix is incomplete')}
}
for(const l of langs){
  const a=contentFor('alphabet',l);
  for(const [group,count] of Object.entries(alphabetExpected[l]))if(count!==null)must((a.groups[group]||[]).length===count,`Alphabet group ${l}/${group} expected ${count}`);
  if(l==='te'){const n=a.groups['హల్లులు'].length;must(a.groups['గుణింతాలు (క్రమబద్ధమైన అభ్యాసం)'].length===n*13,'Telugu gunintalu matrix is incomplete');must(a.groups['అనుస్వార-విసర్గ అభ్యాసం'].length===n*2,'Telugu anusvara-visarga matrix is incomplete')}
  if(l==='hi'){const n=a.groups['व्यंजन'].length;must(a.groups['मात्रा और हलन्त अभ्यास'].length===n*15,'Hindi matra matrix is incomplete')}
  if(l==='kn'){const n=a.groups['ವ್ಯಂಜನಗಳು'].length;must(a.groups['ಸ್ವರಚಿಹ್ನೆ ಮತ್ತು ಒತ್ತಕ್ಷರ ಅಭ್ಯಾಸ'].length===n*15,'Kannada vowel-sign matrix is incomplete')}
  if(l==='ml'){const n=a.groups['വ്യഞ്ജനങ്ങൾ'].length;must(a.groups['സ്വരചിഹ്നവും സംയുക്താക്ഷര-ചിഹ്ന അഭ്യാസവും'].length===n*15,'Malayalam vowel-sign matrix is incomplete')}
}
for(const l of langs){const a=contentFor('alphabet',l);for(const [group,count] of Object.entries(alphabetExpected[l]))must((a.groups[group]||[]).length===count,`Alphabet group ${l}/${group} expected ${count}`)}
for(const l of langs){const fingerprints=new Map();for(const [t] of D.topics)for(const f of formats){const p=`resources/${l}/${t}/${f}.html`;must(fs.existsSync(path.join(root,p)),`Missing resource: ${p}`);if(!fs.existsSync(path.join(root,p)))continue;const x=read(p);must(x.includes(`<html lang="${l}">`),`Wrong language markup: ${p}`);must(x.includes('window.print()'),`Print action missing: ${p}`);must(x.includes('aria-label="Printable learning resource"'),`Printable region missing: ${p}`);must(x.includes(`data-content-key="${l}-${t}-${f}"`),`Missing content identity: ${p}`);must(!x.includes('children ages 3–8'),`Stale age copy: ${p}`);if(t==='alphabet'){const required={en:'ABCDEFGHIJKLMNOPQRSTUVWXYZ',te:'అఆఇఈఉఊఋఎఏఐఒఓఔఅంఅఃకఖగఘఙచఛజఝఞటఠడఢణతథదధనపఫబభమయరలవశషసహళ',hi:'अआइईउऊऋएऐओऔअंअःकखगघङचछजझञटठडढणतथदधनपफबभमयरलवशषसह',ta:'அஆஇஈஉஊஎஏஐஒஓஔக் ச் ட் த் ப் ற் ஃ'.replaceAll(' ',''),kn:'ಅಆಇಈಉಊಋಎಏಐಒಓಔಅಂಅಃಕಖಗಘಙಚಛಜಝಞಟಠಡಢಣತಥದಧನಪಫಬಭಮಯರಲವಶಷಸಹಳ',ml:'അആഇഈഉഊഋഎഏഐഒഓഔഅംഅഃകഖഗഘങചഛജഝഞടഠഡഢണതഥദധനപഫബഭമയരലവശഷസഹളഴറ'};for(const letter of required[l]||'')must(x.includes(letter),`Alphabet resource ${p} is missing character ${letter}`)}const sheet=x.split('<section class="print-sheet"')[1]?.split('</section>')[0]||'';const normalized=sheet.replace(/data-content-key="[^"]+"/g,'').replace(/\s+/g,' ').trim();const prior=fingerprints.get(normalized);if(prior)must(false,`Duplicate printable content in ${l}: ${prior} and ${p}`);else fingerprints.set(normalized,p)}}
const sitemap=read('sitemap.xml');must((sitemap.match(/<url>/g)||[]).length===601,'Sitemap must contain exactly 601 URLs');must(sitemap.includes('https://chitramitra.pages.dev/'),'Sitemap base URL mismatch');
if(fail.length){console.error(`QUALITY GATE FAILED (${fail.length}):`);for(const x of fail.slice(0,100))console.error(`- ${x}`);process.exit(1)}console.log(`Quality gate passed: ${htmlFiles.length} HTML files, 6 languages, 20 topics, 5 formats, unique topic-specific printable content and interactive controls validated.`);
